### ISSUE TITLE
404 error in documentation

### ISSUE THREAD

**Issue by aromot** [mibe/FeedWriter#42]
I wanted to generate an ATOM feed with the library.

I checked the documentation here :

https://mibe.github.io/FeedWriter/namespaces/FeedWriter.html

But when clicking on ATOM, I got a 404 error. Can you fix it so that I can learn how to generate an ATOM feed?

Thank you in advance.

**Comment by mibe** [comment]
First of all sorry for the late reply. I didn't get an issue notification.

I fixed the filename. Thanks for noticing! :+1:

You can also have a look in the [example](https://github.com/mibe/FeedWriter/blob/master/examples/example_atom.php).
