### ISSUE TITLE
tagContent attributes

### ISSUE THREAD

**Issue by mikoczy** [mibe/FeedWriter#44]
Hi!
Is it possible to set attributes for a content element in the channel in RSS2? I'd like to generate something like this:
```
<itunes:category text="Technology">
    <itunes:category text="Tech News"/>
</itunes:category>
```
But I cannot figure out, how to send the attributes to the inner element (if it is possible).
Thank you

**Comment by mibe** [comment]
That is actually not supported, I'm afraid.
And I see no easy way how to implement such a feature...
